import type { Religion } from "@/lib/data"

export type ExtraFestival = {
  slug: string
  title: string
  subtitle: string
  imageQuery: string
  wiki: string
  wikipediaUrl: string
  products: { id: string; title: string; price: string; href: string; imageQuery: string; imageAlt: string }[]
}

// Changed from Record<Religion, ExtraFestival[]> to Record<string, ExtraFestival[]>
export const extraFestivals: Record<string, ExtraFestival[]> = {
  hinduism: [
    {
      slug: "dussehra",
      title: "Dussehra",
      subtitle: "Victory of Good over Evil",
      imageQuery: "dussehra ravana effigy burning celebration",
      wiki: "Dussehra celebrates the victory of Lord Rama over the demon king Ravana, symbolizing the triumph of good over evil. Effigies of Ravana are burned and Ram Leela enactments are staged.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Dussehra",
      products: [
        {
          id: "1",
          title: "Mini Ravana Effigy (Decor)",
          price: "$18",
          href: "https://www.amazon.com",
          imageQuery: "ravana effigy miniature decor",
          imageAlt: "Ravana effigy decor",
        },
        {
          id: "2",
          title: "Festive Pooja Thali",
          price: "$22",
          href: "https://www.amazon.com",
          imageQuery: "pooja thali festive set",
          imageAlt: "Pooja thali",
        },
      ],
    },
    {
      slug: "navratri",
      title: "Navratri",
      subtitle: "Nine Nights of Devi",
      imageQuery: "navratri garba dandiya colorful dance",
      wiki: "A nine-night festival honoring Goddess Durga’s victory over Mahishasura. Devotees fast, dance garba and dandiya, and pray for blessings, wisdom, and protection.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Navaratri",
      products: [
        {
          id: "1",
          title: "Dandiya Sticks (Pair)",
          price: "$12",
          href: "https://www.amazon.com",
          imageQuery: "dandiya sticks wooden colorful",
          imageAlt: "Dandiya sticks",
        },
        {
          id: "2",
          title: "Ghagra Skirt (Navratri)",
          price: "$35",
          href: "https://www.myntra.com",
          imageQuery: "navratri ghagra chaniya choli",
          imageAlt: "Navratri ghagra",
        },
      ],
    },
    {
      slug: "ganesh-chaturthi",
      title: "Ganesh Chaturthi",
      subtitle: "Birth of Lord Ganesha",
      imageQuery: "ganesh chaturthi idol celebration immersion",
      wiki: "Celebrates Lord Ganesh’s birth, the remover of obstacles and harbinger of wisdom. Clay idols are worshipped and immersed in water at the end of the festival.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Ganesh_Chaturthi",
      products: [
        {
          id: "1",
          title: "Eco-friendly Ganesha Idol",
          price: "$28",
          href: "https://www.amazon.com",
          imageQuery: "eco friendly ganesha idol clay",
          imageAlt: "Ganesha idol",
        },
        {
          id: "2",
          title: "Modak Mould Set",
          price: "$10",
          href: "https://www.amazon.com",
          imageQuery: "modak mold set kitchen",
          imageAlt: "Modak mould",
        },
      ],
    },
    {
      slug: "janmashtami",
      title: "Janmashtami",
      subtitle: "Birth of Lord Krishna",
      imageQuery: "janmashtami krishna celebrations matki",
      wiki: "Marks the birth of Lord Krishna; celebrated with fasting, singing, dancing at midnight, and reenactments of Krishna’s childhood.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Krishna_Janmashtami",
      products: [
        {
          id: "1",
          title: "Matki (Decor Pot)",
          price: "$14",
          href: "https://www.amazon.com",
          imageQuery: "matki pot janmashtami decor",
          imageAlt: "Matki decor",
        },
        {
          id: "2",
          title: "Peacock Feather Hairpin",
          price: "$9",
          href: "https://www.amazon.com",
          imageQuery: "peacock feather hairpin",
          imageAlt: "Peacock feather pin",
        },
      ],
    },
    {
      slug: "maha-shivaratri",
      title: "Maha Shivaratri",
      subtitle: "Night of Shiva",
      imageQuery: "maha shivaratri temple night abhishekam",
      wiki: "Devoted to Lord Shiva; night-long prayers, rituals, and fasting to honor Shiva’s cosmic dance and marriage with Parvati.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Maha_Shivaratri",
      products: [
        {
          id: "1",
          title: "Rudraksha Mala",
          price: "$19",
          href: "https://www.amazon.com",
          imageQuery: "rudraksha mala beads",
          imageAlt: "Rudraksha mala",
        },
        {
          id: "2",
          title: "Bael Leaves (Decor)",
          price: "$11",
          href: "https://www.amazon.com",
          imageQuery: "bael leaves puja decor",
          imageAlt: "Bael leaves decor",
        },
      ],
    },
    {
      slug: "makar-sankranti",
      title: "Makar Sankranti",
      subtitle: "Harvest and Kite Festival",
      imageQuery: "makar sankranti kite flying sweets",
      wiki: "A harvest festival celebrating the sun’s transition into Capricorn; marked by kite flying, sweets, and bathing in holy rivers for blessings.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Makar_Sankranti",
      products: [
        {
          id: "1",
          title: "Kite & Manjha Set",
          price: "$16",
          href: "https://www.amazon.com",
          imageQuery: "kite and manjha set",
          imageAlt: "Kite set",
        },
        {
          id: "2",
          title: "Sesame Jaggery Sweets",
          price: "$8",
          href: "https://www.amazon.com",
          imageQuery: "til gud sweets sesame jaggery",
          imageAlt: "Til-gud sweets",
        },
      ],
    },
  ],
  islam: [
    {
      slug: "eid-al-adha",
      title: "Eid al-Adha",
      subtitle: "Festival of Sacrifice",
      imageQuery: "eid al adha lantern crescent feast",
      wiki: "Festival of Sacrifice commemorating Ibrahim’s devotion; observed with prayers, charity, and sharing food.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Eid_al-Adha",
      products: [
        {
          id: "1",
          title: "Elegant Prayer Mat",
          price: "$20",
          href: "https://www.amazon.com",
          imageQuery: "muslim prayer mat elegant",
          imageAlt: "Prayer mat",
        },
        {
          id: "2",
          title: "Lantern String Lights",
          price: "$15",
          href: "https://www.amazon.com",
          imageQuery: "eid lantern string lights",
          imageAlt: "Lantern lights",
        },
      ],
    },
    {
      slug: "ramadan",
      title: "Ramadan",
      subtitle: "Month of Fasting",
      imageQuery: "ramadan iftar dates lantern quran",
      wiki: "Month of daytime fasting, prayer, and reflection culminating in Eid al-Fitr.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Ramadan",
      products: [
        {
          id: "1",
          title: "Premium Dates Box",
          price: "$18",
          href: "https://www.amazon.com",
          imageQuery: "premium dates gift box",
          imageAlt: "Dates box",
        },
        {
          id: "2",
          title: "Table Lantern",
          price: "$22",
          href: "https://www.amazon.com",
          imageQuery: "ramadan lantern table decor",
          imageAlt: "Decor lantern",
        },
      ],
    },
    {
      slug: "muharram",
      title: "Muharram",
      subtitle: "Islamic New Year",
      imageQuery: "muharram islamic new year reflection",
      wiki: "Marks the Islamic New Year and commemorates the martyrdom of Imam Hussain.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Muharram",
      products: [
        {
          id: "1",
          title: "Tasbih Prayer Beads",
          price: "$12",
          href: "https://www.amazon.com",
          imageQuery: "tasbih prayer beads wood",
          imageAlt: "Tasbih",
        },
        {
          id: "2",
          title: "Black Abaya (Modest)",
          price: "$32",
          href: "https://www.amazon.com",
          imageQuery: "abaya black modest wear",
          imageAlt: "Abaya",
        },
      ],
    },
    {
      slug: "milad-un-nabi",
      title: "Milad-un-Nabi",
      subtitle: "Prophet’s Birthday",
      imageQuery: "mawlid celebration lights mosque",
      wiki: "Birthday of Prophet Muhammad, observed with prayers, sermons, and community gatherings.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Mawlid",
      products: [
        {
          id: "1",
          title: "Green Mosque Decor",
          price: "$14",
          href: "https://www.amazon.com",
          imageQuery: "green mosque decor ornament",
          imageAlt: "Mosque decor",
        },
        {
          id: "2",
          title: "Sweets Assortment",
          price: "$10",
          href: "https://www.amazon.com",
          imageQuery: "middle eastern sweets box",
          imageAlt: "Sweets",
        },
      ],
    },
    {
      slug: "laylat-al-qadr",
      title: "Laylat al-Qadr",
      subtitle: "Night of Power",
      imageQuery: "laylat al qadr night prayer mosque lights",
      wiki: "Considered the holiest night within Ramadan, devoted to prayer and seeking forgiveness.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Laylat_al-Qadr",
      products: [
        {
          id: "1",
          title: "Quran Stand (Rehal)",
          price: "$16",
          href: "https://www.amazon.com",
          imageQuery: "quran stand rehal wood",
          imageAlt: "Quran stand",
        },
        {
          id: "2",
          title: "Night Lamp Crescent",
          price: "$18",
          href: "https://www.amazon.com",
          imageQuery: "crescent moon night lamp",
          imageAlt: "Crescent lamp",
        },
      ],
    },
    {
      slug: "hajj",
      title: "Hajj",
      subtitle: "Pilgrimage to Mecca",
      imageQuery: "hajj kaaba pilgrims mecca",
      wiki: "Annual pilgrimage to Mecca and one of the five pillars of Islam.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Hajj",
      products: [
        {
          id: "1",
          title: "Ihram Towel Set",
          price: "$25",
          href: "https://www.amazon.com",
          imageQuery: "ihram towel set pilgrimage",
          imageAlt: "Ihram towels",
        },
        {
          id: "2",
          title: "Travel Prayer Kit",
          price: "$13",
          href: "https://www.amazon.com",
          imageQuery: "travel prayer kit compact",
          imageAlt: "Travel prayer kit",
        },
      ],
    },
  ],
  christianity: [
    {
      slug: "good-friday",
      title: "Good Friday",
      subtitle: "Passion of Christ",
      imageQuery: "good friday cross reflection church",
      wiki: "Commemorates the crucifixion of Jesus Christ and his sacrifice.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Good_Friday",
      products: [
        {
          id: "1",
          title: "Wooden Cross Decor",
          price: "$16",
          href: "https://www.amazon.com",
          imageQuery: "wooden cross wall decor",
          imageAlt: "Wooden cross",
        },
        {
          id: "2",
          title: "Candle Set (White)",
          price: "$9",
          href: "https://www.amazon.com",
          imageQuery: "white candles set",
          imageAlt: "Candles",
        },
      ],
    },
    {
      slug: "easter",
      title: "Easter",
      subtitle: "Resurrection Sunday",
      imageQuery: "easter lilies sunrise church celebration",
      wiki: "Celebrates Jesus’s resurrection from the dead.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Easter",
      products: [
        {
          id: "1",
          title: "Easter Egg Dye Kit",
          price: "$11",
          href: "https://www.amazon.com",
          imageQuery: "easter egg dye kit",
          imageAlt: "Egg dye kit",
        },
        {
          id: "2",
          title: "Spring Wreath",
          price: "$18",
          href: "https://www.amazon.com",
          imageQuery: "spring wreath door decor",
          imageAlt: "Spring wreath",
        },
      ],
    },
    {
      slug: "palm-sunday",
      title: "Palm Sunday",
      subtitle: "Entry into Jerusalem",
      imageQuery: "palm sunday palms church procession",
      wiki: "Marks Jesus’s entry into Jerusalem.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Palm_Sunday",
      products: [
        {
          id: "1",
          title: "Palm Leaf Cross (Pack)",
          price: "$10",
          href: "https://www.amazon.com",
          imageQuery: "palm leaf cross pack",
          imageAlt: "Palm crosses",
        },
        {
          id: "2",
          title: "Hymns Booklet",
          price: "$8",
          href: "https://www.amazon.com",
          imageQuery: "church hymns booklet",
          imageAlt: "Hymns booklet",
        },
      ],
    },
    {
      slug: "pentecost",
      title: "Pentecost",
      subtitle: "Descent of the Holy Spirit",
      imageQuery: "pentecost dove flame church",
      wiki: "Honors the descent of the Holy Spirit on the apostles.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Pentecost",
      products: [
        {
          id: "1",
          title: "Dove Symbol Pendant",
          price: "$15",
          href: "https://www.amazon.com",
          imageQuery: "dove pendant necklace",
          imageAlt: "Dove pendant",
        },
        {
          id: "2",
          title: "Red Altar Cloth",
          price: "$20",
          href: "https://www.amazon.com",
          imageQuery: "red altar cloth church",
          imageAlt: "Red altar cloth",
        },
      ],
    },
    {
      slug: "maundy-thursday",
      title: "Maundy Thursday",
      subtitle: "Last Supper",
      imageQuery: "maundy thursday last supper bread wine",
      wiki: "Remembers the Last Supper of Jesus with his disciples.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Maundy_Thursday",
      products: [
        {
          id: "1",
          title: "Communion Set (Decor)",
          price: "$22",
          href: "https://www.amazon.com",
          imageQuery: "communion set chalice plate",
          imageAlt: "Communion set",
        },
        {
          id: "2",
          title: "Bread Board & Knife",
          price: "$18",
          href: "https://www.amazon.com",
          imageQuery: "bread board and knife set",
          imageAlt: "Bread board",
        },
      ],
    },
  ],
  sikh: [
    {
      slug: "guru-nanak-gurpurab",
      title: "Guru Nanak Gurpurab",
      subtitle: "Birth of Guru Nanak",
      imageQuery: "guru nanak gurpurab gurudwara celebration",
      wiki: "Birth anniversary of Guru Nanak, with prayers, hymn singing, and community meals.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Guru_Nanak",
      products: [
        {
          id: "1",
          title: "Khanda Wall Emblem",
          price: "$17",
          href: "https://www.amazon.com",
          imageQuery: "khanda wall emblem metal",
          imageAlt: "Khanda emblem",
        },
        {
          id: "2",
          title: "Harmonium Practice Book",
          price: "$12",
          href: "https://www.amazon.com",
          imageQuery: "harmonium practice book",
          imageAlt: "Harmonium book",
        },
      ],
    },
    {
      slug: "guru-gobind-singh-jayanti",
      title: "Guru Gobind Singh Jayanti",
      subtitle: "Birth of the Tenth Guru",
      imageQuery: "guru gobind singh jayanti celebration",
      wiki: "Commemorates the birth of the tenth Sikh Guru.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Guru_Gobind_Singh",
      products: [
        {
          id: "1",
          title: "Mini Kirpan (Decor)",
          price: "$19",
          href: "https://www.amazon.com",
          imageQuery: "kirpan miniature decor",
          imageAlt: "Kirpan decor",
        },
        {
          id: "2",
          title: "Turban Cloth (Pagri)",
          price: "$16",
          href: "https://www.amazon.com",
          imageQuery: "turban cloth sikh pagri",
          imageAlt: "Turban cloth",
        },
      ],
    },
    {
      slug: "hola-mohalla",
      title: "Hola Mohalla",
      subtitle: "Martial Exercises & Spirit",
      imageQuery: "hola mohalla nihang martial display",
      wiki: "Hola Mohalla features martial arts demonstrations and spiritual gatherings.",
      wikipediaUrl: "https://en.wikipedia.org/wiki/Hola_Mohalla",
      products: [
        {
          id: "1",
          title: "Nihang Turban Accessory",
          price: "$14",
          href: "https://www.amazon.com",
          imageQuery: "nihang turban accessory chakram",
          imageAlt: "Turban accessory",
        },
        {
          id: "2",
          title: "Sports Arm Guard",
          price: "$12",
          href: "https://www.amazon.com",
          imageQuery: "arm guard sports protective gear",
          imageAlt: "Arm guard",
        },
      ],
    },
  ],
}
