# Name of the workflow
name: Deploy Next.js site to Pages

# Run this workflow on pushes to the 'main' branch
on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Get the code from your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Node.js (using your version 20.x)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build the static site
      - name: Build with Next.js
        run: npm run build

      # 5. Prepare the artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This should match the output directory of your Next.js build
          path: ./out

  # Deployment job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 6. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4